### ISSUE TITLE
Initial iteration on theming

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1076]
### Context

We need a way to allow the developers to change the appearance of Avo.
The initial iteration will cover adding custom CSS variables to a configuration path to get loaded in the front-end.

### Initial configuration:

- [ ] primary and secondary colors
- [ ] border-radius (maybe)

### Tasks: 

- [ ] add configuration for CSS variables (ruby DSL)
- [ ] output the configuration on the front-end
- [ ] customize Tailwind to take them into account
- [ ] change the classes to use that configuration
- [ ] apply the system throughout the app

## Second iteration

- [ ] package up that configuration and install it as a gem
- [ ] change the logo with that configuration

**Comment by adrianthedev** [comment]
Closing in favour of https://github.com/avo-hq/avo/issues/631
