### ISSUE TITLE
`avo-advanced`, `avo-dashboards`, `avo-dynamic_filters`, `avo-menu`, and `avo-pro` all depend on `rails` instead of specific components.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1987]
### Describe the bug

The new gems you've broken functionality out into all have direct dependencies on Rails instead of on specific Rails components they rely on.  This is resulting in our app including a bunch of components we have no need of and prefer not to include.  (`actionmailbox`, and `actioncable` -- and by extension, `websocket-driver`, and `websocket-extensions`).

I know you put effort into addressing this in Avo 2 (thank you!), and that effort has survived into the core gem for Avo 3 so this is something of a regression.

### Steps to Reproduce
1. Add Avo Pro or Advanced gems to project.
2. Ensure `Gemfile` for project only includes specific Rails components, not `rails` itself.
3. `bundle`
4. See `Gemfile.lock`

### Expected behavior & Actual behavior

Ideally each gem should depend exactly and only on the components that it cannot function without.

For functionality that the user may or may not use which depends on a Rails component, the docs should indicate that dependency and warnings/errors should be presented to the user at runtime if they try to use such an optional feature when they have not included the relevant Rails component in their bundle.

### System configuration
**Avo version**: 3.0.1.beta22

**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

P.S. Are you guys planning on updating this template to include Advanced as an option?

**Are you using Avo monkey patches, overriding views or view components?**

 - [x] Yes. If so, please post code samples.
 - [ ] No

(Not applicable here.)

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

For scale:  I am concerned about the inclusion of needless dependencies in general for a bunch of reasons but the ones relevant here basically boil down to:

1. More stuff to install increases AMI build time, and once that gets bad, pruning it down is really hard -- so I prefer to stay on top of it so it doesn't reach an unacceptable threshold.
2. Code that isn't installed can't be leveraged in an exploit.  Ruby and Rails have a history of exploits in which code that's present on the system but not actually used by an app can be used by an attacker.  Notable example being waaay back before `safe_yaml` when an attacker could present Yaml to an API that represented serialized objects and could thus force the serve to instantiate any class present in the Ruby VM.  We're in a security-sensitive position (we have access to peoples' Gmail accounts!), and subject to routine security audits.

Since we're talking about Rails core components and their direct dependencies, these concerns are both _relatively_ mild, but `websocket-driver` _does_ include a native extension which is _potentially_ material to both AMI build times and the security profile of the system.
```[tasklist]
### Tasks
- [ ] avo-advanced
- [ ] avo-dashboards
- [ ] avo-dynamic_filters
- [ ] avo-menu
- [ ] avo-pro
```

**Comment by MrJoy** [comment]
Any chance of movement on this?

**Comment by adrianthedev** [comment]
I agree with this approach. We use it with Avo 2, but missed it with Avo 3 gems.
It's on the roadmap!
