### ISSUE TITLE
Countless pagination translations

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#2027]
Translation needed on [this PR](https://github.com/avo-hq/avo/pull/1998) for:
```yml
records_selected_from_all_pages_html: All records selected from all pages
x_records_selected_from_page_html: <span class="font-bold text-gray-700">%{selected}</span> records selected on this page
```
## `records_selected_from_all_pages_html`
![image](https://github.com/avo-hq/avo/assets/69730720/ced9343f-6237-4ec4-abd3-22f9d6e3633a)

## `x_records_selected_from_page_html`
![image](https://github.com/avo-hq/avo/assets/69730720/d2ec857c-930b-4968-bdc8-e39a0fa4c683)

```[tasklist]
### Tasks
- [ ] avo.ar.yml
- [x] avo.fr.yml
- [ ] avo.nb.yml
- [ ] avo.nn.yml
- [ ] avo.tr.yml
- [ ] avo.es.yml
```

**Comment by jetienne** [comment]
@Paul-Bob FR:

records_selected_from_all_pages_html : tous les éléments sélectionnés de toutes les pages
x_records_selected_from_page_html : <span class="font-bold text-gray-700">%{selected}</span> éléments sélectionnés de cette page

**Comment by Paul-Bob** [comment]
Thank you for the prompt response @jetienne !

**Comment by Paul-Bob** [comment]
Google translated it
